spring.datasource.url=jdbc:mysql://movie-booking-db-trantannd01-f433.e.aivencloud.com:23481/movie_booking?useSSL=true&trustServerCertificate=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_--jFp1qMe1nH4m8kx5il
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.devtools.add-properties=true
server.port=8080

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

app.qr.secret-salt=YourStrongSalt@2025
blockchain.node.enabled=false
blockchain.node.url=http://localhost:8545
blockchain.contract.address=0x0000000000000000000000000000000000000000

payos.client-id=9be14e8b-3178-415e-bbbb-e98bc78ec94a
payos.api-key=6fe9e92d-c72f-4a37-a2be-3941ae52b4fe
payos.checksum-key=8ff7c2e8e4ebfd98bfb918ceaa923ce5203d609d5e57eeef28cfca5bba5d6259

payos.return-url=http://localhost:5173/payment/success
payos.cancel-url=http://localhost:5173/payment/cancel